name: Generate manifest.json

on:
  push:
    branches: [ main ]

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install fs-extra

      - name: Generate manifest.json
        run: node generate-manifest.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Auto-update manifest.json" || echo "No changes to commit"
          git push
